[project]
name = "call-my-agent"
version = "0.1.0"
description = "Run opencode in container and manage installs with brew"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "sqlmodel>=0.0.31",
]

[dependency-groups]
dev = [
    "pyright>=1.1.408",
]
